name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    # Mudamos para 22.04 para evitar conflitos de versões novas de Python/Pip
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Buildozer stats
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable
        env:
          USER: root
          # Essa linha abaixo pula o erro de "externally-managed-environment"
          PIP_BREAK_SYSTEM_PACKAGES: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Hanzod-APK
          path: bin/*.apk